{
    "swagger": "2.0",
    "info": {
        "title": "SIM-CITY webservice",
        "version": "",
        "description": "The [SIM-CITY webservice](http://github.com/NLeSC/sim-city-webservice) starts\nsimulations and jobs using the\n[SIM-CITY client](http://github.com/NLeSC/sim-city-client).\n\n"
    },
    "host": "simcity.amsterdam-complexity.nl",
    "basePath": "/explore",
    "schemes": [
        "https"
    ],
    "paths": {
        "/": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {}
                    }
                },
                "summary": "API specification",
                "description": "Swagger 2.0 API schema.\n\n",
                "tags": [
                    "API"
                ],
                "parameters": []
            }
        },
        "/doc": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {}
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "documentation type [type] not found, choose between [options]"
                            }
                        }
                    }
                },
                "summary": "API documentation",
                "description": "This page, or with another `Accept` header, the raw API Blueprint (text/markdown) or Swagger (application/json) documentation.\n\n\n",
                "tags": [
                    "API"
                ],
                "parameters": [],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/job": {
            "post": {
                "responses": {
                    "201": {
                        "description": "Created",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "_id": "job_hostname-uuid-seconds",
                                "batch_id": "103024",
                                "hostname": "example.com"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "description": "job id"
                                },
                                "batch_id": {
                                    "type": "string",
                                    "description": "job id according to the queueing system"
                                },
                                "hostname": {
                                    "type": "string",
                                    "description": "hostname of the queueing system it was submitted to"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "headers": {},
                        "examples": {}
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "headers": {},
                        "examples": {}
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "headers": {},
                        "examples": {}
                    }
                },
                "summary": "Submit job",
                "description": "Start a job. Unless host is given, start the job on the default host.\n\n",
                "tags": [
                    "Jobs"
                ],
                "parameters": [
                    {
                        "name": "host",
                        "in": "query",
                        "description": "Host to start job on; one of the hosts given in /hosts.",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/hosts": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "host1": {
                                    "default": true
                                },
                                "host2": {}
                            }
                        }
                    }
                },
                "summary": "Configured hosts",
                "description": "Retrieve hosts configured under the webservice with basic (optional) metadata.\n\n",
                "tags": [
                    "Jobs"
                ],
                "parameters": [],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/simulate": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "simulation malconfigured on server"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message"
                                }
                            }
                        }
                    }
                },
                "summary": "Simulation engines",
                "description": "Get the names of the simulation engines configured in the webservice.\n\n",
                "tags": [
                    "Simulations"
                ],
                "parameters": [],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/simulate/{name}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "name": "simulation1",
                                "versions": [
                                    "0.1",
                                    "latest"
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "simulation name is malformed"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "Simulation 'sim3' not found."
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "simulation malconfigured on server"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message"
                                }
                            }
                        }
                    }
                },
                "summary": "Simulation engine versions",
                "description": "Get the versions of a simulation engine and their configurations.\n\n",
                "tags": [
                    "Simulations"
                ],
                "parameters": [
                    {
                        "name": "name",
                        "in": "path",
                        "description": "Name of the simulation engine",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/simulate/{name}/{version}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "name": "simulation1",
                                "version": "0.01",
                                "command": "path/to/sim-city-client/simulation.py",
                                "parameters": [
                                    {
                                        "name": "model",
                                        "type": "choice",
                                        "choices": [
                                            "type1",
                                            "type2"
                                        ],
                                        "default": "type1",
                                        "description": "model instance to run"
                                    },
                                    {
                                        "name": "name",
                                        "type": "str",
                                        "min_length": 3,
                                        "max_length": 32
                                    },
                                    {
                                        "name": "simitems",
                                        "type": "number",
                                        "min": 0,
                                        "max": 100,
                                        "dtype": "float"
                                    }
                                ]
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "Version '0.5' of simulation 'sim1' not found."
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message."
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "simulation malconfigured on server"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message."
                                }
                            }
                        }
                    }
                },
                "summary": "Configuration",
                "description": "Get the configuration and parameter specifications of a version of a simulation\nengine.\n\n",
                "tags": [
                    "Simulations"
                ],
                "parameters": [
                    {
                        "name": "name",
                        "in": "path",
                        "description": "Name of the simulation engine",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "version",
                        "in": "path",
                        "description": "Simulation engine version. This may include\nversion references like \"latest\" or \"stable\".\n\n",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ]
            },
            "post": {
                "responses": {
                    "201": {
                        "description": "Created",
                        "headers": {},
                        "examples": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "Version '0.5' of simulation 'sim1' not found."
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "simulation name task_12345 already taken"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message."
                                }
                            }
                        }
                    },
                    "412": {
                        "description": "Precondition Failed",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "input is not json or does not validate against the parameters schema."
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "simulation malconfigured on server"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message"
                                }
                            }
                        }
                    }
                },
                "summary": "Start simulation",
                "description": "Start a new simulation using the simulation engine. Parameters required by\nthe simulation engine should be provided in the request.\n\n",
                "tags": [
                    "Simulations"
                ],
                "parameters": [
                    {
                        "name": "name",
                        "in": "path",
                        "description": "Name of the simulation engine",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "version",
                        "in": "path",
                        "description": "Simulation engine version. This may include\nversion references like \"latest\" or \"stable\".\n\n",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "required": [
                                "ensemble",
                                "simulation_specific_parameters"
                            ],
                            "properties": {
                                "_id": {
                                    "type": "string"
                                },
                                "ensemble": {
                                    "type": "string"
                                },
                                "simulation_specific_parameters": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/simulation/{id}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "_id": "task_12345",
                                "_rev": "3-abcdef",
                                "name": "sim1",
                                "output": {},
                                "lock": 1439388534,
                                "hostname": "myhost.example.com",
                                "scrub_count": 0,
                                "version": "0.3",
                                "command": "~/path/to/command.py",
                                "uploads": {
                                    "file1.json": "http://webdav.example.com/sim1/file1.json"
                                },
                                "execute_properties": {
                                    "dirs": {
                                        "tmp": "/scratch/local/task_12345",
                                        "input": "/home/me/sim1/input/task_12345",
                                        "output": "/home/me/sim1/output/task_12345"
                                    },
                                    "input_file": "/home/me/sim1/input/task_12345/input.json"
                                },
                                "error": [],
                                "done": 1439390617,
                                "type": "task",
                                "ensemble": "myensemble",
                                "input": {
                                    "param1": 21,
                                    "locations1": {
                                        "id": "Netherlands eScience Center",
                                        "x": "52.356923",
                                        "y": "4.954268"
                                    }
                                },
                                "_attachments": {
                                    "file2.json": {
                                        "content_type": "application/json",
                                        "revpos": 3,
                                        "digest": "md5-mYQqQM/2nHpccWNnvwqI8g==",
                                        "length": 515418,
                                        "stub": true
                                    }
                                }
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "_id": {
                                    "type": "string",
                                    "description": "simulation id"
                                },
                                "_rev": {
                                    "type": "string",
                                    "description": "simulation revision in the database"
                                },
                                "name": {
                                    "type": "string",
                                    "description": "simulation engine name"
                                },
                                "version": {
                                    "type": "string",
                                    "description": "simulation engine version"
                                },
                                "ensemble": {
                                    "type": "string",
                                    "description": "ensemble name"
                                },
                                "hostname": {
                                    "type": "string",
                                    "description": "hostname that the simulation was run on"
                                },
                                "command": {
                                    "type": "string",
                                    "description": "command that will run the simulation"
                                },
                                "lock": {
                                    "type": "number",
                                    "description": "time in seconds that computation on the task started (0 if none, -1 if error)"
                                },
                                "done": {
                                    "type": "number",
                                    "description": "time in seconds that computation on the task finished (0 if none, -1 if error)"
                                },
                                "uploads": {
                                    "type": "object",
                                    "properties": {
                                        "some_filename": {
                                            "type": "string",
                                            "description": "URL of file"
                                        }
                                    },
                                    "description": "uploaded files, filename and URL"
                                },
                                "input": {
                                    "type": "object",
                                    "properties": {},
                                    "description": "input parameters for the simulation."
                                },
                                "output": {
                                    "type": "object",
                                    "properties": {},
                                    "description": "output value from the simulation."
                                },
                                "_attachments": {
                                    "type": "object",
                                    "properties": {
                                        "some_filename": {
                                            "type": "object",
                                            "properties": {
                                                "content_type": {
                                                    "type": "string",
                                                    "description": "content type of attachment"
                                                },
                                                "length": {
                                                    "type": "number",
                                                    "description": "length in bytes"
                                                },
                                                "digest": {
                                                    "type": "string",
                                                    "description": "digest of the contents"
                                                },
                                                "revpos": {
                                                    "type": "number",
                                                    "description": "document revision that the file was added or updated"
                                                },
                                                "stub": {
                                                    "type": "boolean",
                                                    "description": "whether the attachment data is contained in the object"
                                                },
                                                "data": {
                                                    "type": "string",
                                                    "description": "actual attachment data"
                                                }
                                            }
                                        }
                                    },
                                    "description": "files attached to the couchdb document."
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "simulation does not exist"
                            }
                        }
                    }
                },
                "summary": "Simulation",
                "description": "",
                "tags": [
                    "Simulations"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Simulation id",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ]
            },
            "delete": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "ok": true
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "resource conflict or revision not specified"
                            }
                        }
                    }
                },
                "summary": "Delete simulation",
                "description": "",
                "tags": [
                    "Simulations"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Simulation id",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "rev",
                        "in": "query",
                        "description": "Revision of simulation, as retrieved from a previous get request.",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/resource": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "resources": [
                                    "type1",
                                    "type2"
                                ]
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "resources": {
                                    "type": "array",
                                    "description": "resource names"
                                }
                            }
                        }
                    }
                },
                "summary": "Resource type list",
                "description": "Get the names of the resource types configured in the webservice.\n\n",
                "tags": [
                    "Resources"
                ],
                "parameters": [],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/resource/{name}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "id": "matsim",
                                "title": "matsim",
                                "featureTypes": {
                                    "FireStation": {
                                        "id": "SimCity#firestation",
                                        "name": "FireStation",
                                        "style": {
                                            "drawingMode": "Point",
                                            "iconUri": "images/brandweerposten/Brandweerkazerne.png",
                                            "cornerRadius": 50,
                                            "fillColor": "#ffffff",
                                            "iconWidth": 30,
                                            "iconHeight": 30,
                                            "strokeColor": "#ffffff"
                                        },
                                        "propertyTypeKeys": "title,notes",
                                        "u": "bower_components/csweb/dist-bower/images/marker.png"
                                    },
                                    "Fire": {
                                        "id": "SimCity#fire",
                                        "name": "Fire",
                                        "style": {
                                            "drawingMode": "Point",
                                            "iconUri": "data/images/fire.png",
                                            "cornerRadius": 50,
                                            "fillColor": "#ffffff",
                                            "iconWidth": 30,
                                            "iconHeight": 30,
                                            "strokeColor": "#ffffff"
                                        },
                                        "propertyTypeKeys": "title,notes",
                                        "u": "bower_components/csweb/dist-bower/images/marker.png"
                                    }
                                },
                                "propertyTypeData": {},
                                "isDynamic": false
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "Resource type 'type1' not found."
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message."
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "Resource type malconfigured on server"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message."
                                }
                            }
                        }
                    }
                },
                "summary": "Resource type definition",
                "description": "Get the resource type.\n\n",
                "tags": [
                    "Resources"
                ],
                "parameters": [
                    {
                        "name": "name",
                        "in": "path",
                        "description": "Name of the resource type",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/schema": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "resources": [
                                    "schema1",
                                    "schema2"
                                ]
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "resources": {
                                    "type": "array",
                                    "description": "schema names"
                                }
                            }
                        }
                    }
                },
                "summary": "Schema list",
                "description": "Get the names of the schemas configured in the webservice.\n\n",
                "tags": [
                    "Schemas"
                ],
                "parameters": [],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/schema/{name}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "Resource type 'schema1' not found."
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message."
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "Resource type malconfigured on server"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message."
                                }
                            }
                        }
                    }
                },
                "summary": "Resource type definition",
                "description": "Get the resource type.\n\n",
                "tags": [
                    "Schemas"
                ],
                "parameters": [
                    {
                        "name": "name",
                        "in": "path",
                        "description": "Name of the resource type",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/view/totals": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "pending": 0,
                                "in_progress": 0,
                                "done": 0,
                                "error": 0,
                                "pending_jobs": 0,
                                "running_jobs": 0,
                                "finished_jobs": 0,
                                "archived_jobs": 0,
                                "active_jobs": 0
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "pending": {
                                    "type": "number",
                                    "description": "number of tasks to be done"
                                },
                                "in_progress": {
                                    "type": "number",
                                    "description": "number of tasks currently being processed"
                                },
                                "done": {
                                    "type": "number",
                                    "description": "number of tasks done processing"
                                },
                                "error": {
                                    "type": "number",
                                    "description": "number of tasks that resulted in error"
                                },
                                "pending_jobs": {
                                    "type": "number",
                                    "description": "number of jobs submitted but not started"
                                },
                                "running_jobs": {
                                    "type": "number",
                                    "description": "number of jobs currently being processed. This number may include jobs that were stopped before reporting that they were finished."
                                },
                                "finished_jobs": {
                                    "type": "number",
                                    "description": "number of jobs that have finished processing. This number may include jobs that have reported finished but failed to be reported as queued."
                                },
                                "archived_jobs": {
                                    "type": "number",
                                    "description": "number of jobs that were archived after completing the entire pipeline of pending to finished."
                                },
                                "active_jobs": {
                                    "type": "number",
                                    "description": "number of jobs that have not been archived."
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "headers": {},
                        "examples": {
                            "application/json": {
                                "error": "failed to retrieve overview"
                            }
                        },
                        "schema": {
                            "$schema": "http://json-schema.org/draft-04/schema#",
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string",
                                    "description": "error message"
                                }
                            }
                        }
                    }
                },
                "summary": "Overview",
                "description": "Total number of jobs and tasks, categorized by status\n\n",
                "tags": [
                    "Monitoring"
                ],
                "parameters": [],
                "produces": [
                    "application/json"
                ]
            }
        },
        "/view/simulations/{name}/{version}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "examples": {}
                    },
                    "302": {
                        "description": "Found",
                        "headers": {},
                        "examples": {}
                    }
                },
                "summary": "Active simulations",
                "description": "Simulations configured for a certain simulation engine. If the ensemble name\nis given, only simulations for that ensemble are shown. Even if the result is\nprovided directly by a CouchDB database, the call to the webservice is needed\nto ensure that the correct database view exists.\n\n",
                "tags": [
                    "Monitoring"
                ],
                "parameters": [
                    {
                        "name": "name",
                        "in": "path",
                        "description": "simulation engine name",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "version",
                        "in": "path",
                        "description": "simulation engine version",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "ensemble",
                        "in": "query",
                        "description": "ensemble name",
                        "required": false,
                        "type": "string"
                    }
                ]
            }
        }
    },
    "definitions": {
        "API specification": {},
        "API documentation": {},
        "Submit job": {},
        "Configured hosts": {},
        "Simulation engines": {},
        "Simulation engine versions": {},
        "Specific simulation engine": {},
        "Simulation": {},
        "Resource type list": {},
        "Resource type definition": {},
        "Schema list": {},
        "Overview": {},
        "Active simulations": {}
    }
}